live/urls.py
from django.urls import path
from . import views

urlpatterns = [
path('<str:course>/<str:order>/<int:classno>', views.startLive, name='startLive'),
path('join/<str:course>/<str:order>/<int:classno>', views.joinLive, name='joinLive'),
path('closeLive/', views.closeLive, name='closeLive'),
path('closepage/', views.closepage, name='closepage'),


]

vschool/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path,include

from . import views

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
]


urlpatterns += i18n_patterns(
    path('mesho/', admin.site.urls),
    path('',views.home, name='home'),
    path('courses/',include('courses.urls')),
    path('users/',include('users.urls')),
    path('Notifs/',include('Notifs.urls')),
    path('orders/',include('orders.urls')),
    path('Teachers/',include('Teachers.urls')),
    path('live/',include('live.urls')),
    path('admin/',include('admin_honeypot.urls', namespace='admin_honeypot')),


)+ static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)


handler404 = 'vschool.views.handler404'
handler500 = 'vschool.views.handler500'

users/models.py
import os
from django.db import models
from django import forms
from django.db import models

# Create your models here.
#overwrite django user model
from django.db import models
from django.contrib.auth.models import AbstractBaseUser ,BaseUserManager
from django.db.models.signals import post_save
from django.template.loader import render_to_string
import django.core.mail

from Notifs.models import Inboxnotif
from vschool import settings


class account_manger(BaseUserManager):
    def create_user(self,first_name,last_name,email,username,password=None):
        if not email:
            raise ValueError('add your email')
        if not username:
            raise ValueError('add username')
        user = self.model(
            email = self.normalize_email(email),
            username = username,
            first_name = first_name,
            last_name = last_name
        )
        user.set_password(password)
        user.save(using=self._db)


        return user

    def create_superuser(self, first_name, last_name, email, username, password):
        user = self.create_user(
            email=self.normalize_email(email),
            username=username,
            first_name=first_name,
            last_name=last_name,
            password = password
        )
        user.is_admin = True
        user.is_superadmin = True
        user.is_staff = True
        user.is_active = True
        user.save(using=self._db)
        return user
class account(AbstractBaseUser):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField(max_length=100,unique=True)
    username = models.CharField(max_length=50)
    phone = models.CharField(max_length=20)
    user_img = models.ImageField(upload_to="img/users", blank=True, default='default_avatar.png')
    #required
    joined_date = models.DateTimeField(auto_now_add=True)
    last_login = models.DateTimeField(auto_now_add=True)
    is_superadmin = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username','first_name','last_name']
    objects = account_manger()
    def __str__(self):
        return self.email
    #must mention in overwrite
    def has_perm(self,perm,obj=None):
        return self.is_admin
    def has_module_perms(self,add_label):
        return True

    @property
    def image_url(self):
        DEFAULT = 'default_avatar.png'

        if self.user_img and hasattr(self.user_img, 'url'):
            return self.user_img.url
        else:
            self.user_img = DEFAULT
            return self.user_img

    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            UserProfile.objects.create(user=instance)
            mail_subject = 'user(not teacher) registration'
            mail_body = render_to_string('teachers/teacherRegistrationMail.html', { 'user':instance  })
            to_email = 'info@myschools.site'
            send_mail = django.core.mail.EmailMessage(mail_subject, mail_body, to=[to_email],from_email='info@myschools.site')
            send_mail.send()





    def delete(self, *args, **kwargs):
        DEFAULT = 'default_avatar.png'
        os.remove(os.path.join(settings.MEDIA_ROOT, self.user_img.name))
        self.user_img = DEFAULT
        super(account, self).delete(*args, **kwargs)






class UserProfile(models.Model):
    user = models.OneToOneField(account,on_delete=models.CASCADE)
    city = models.CharField(max_length=20,blank=True)
    country = models.CharField(max_length=20,blank=True)
    def __str__(self):
        return self.user.first_name

class Inbox(models.Model):
    sender = models.ForeignKey(account, on_delete=models.SET_NULL, null=True, blank=True,related_name="sentMessages")
    recipient = models.ForeignKey(account, on_delete=models.SET_NULL, null=True, blank=True, related_name="messages")
    subject = models.CharField(max_length=200, null=True, blank=True)
    body = models.TextField()

    is_read = models.BooleanField(default=False, null=True)
    created = models.DateTimeField(auto_now_add=True)
    is_sender_delete = models.BooleanField(default=False)
    is_receiver_delete = models.BooleanField(default=False)

    def notify(sender,instance,created,*args,**kwargs):

        Inbox = instance
        sender = Inbox.sender
        recipient = Inbox.recipient
        Message = f'{sender.first_name} sent you email.'
        if created and Inbox.id is not None:
            notifs = Inboxnotif(sender=sender,recipient=recipient,Message=Message,message_id=Inbox.id,notif_type=1)
            notifs.save()


    def __str__(self):
        return self.subject

    class Meta:
        ordering = ['is_read', '-created']
post_save.connect(Inbox.notify,sender=Inbox)
post_save.connect(account.create_user_profile,sender=account)
class Vists(models.Model):
    ip = models.GenericIPAddressField()
    created = models.DateTimeField(auto_now_add=True)
    country=models.CharField(max_length=150,null=True,default="NA")
    city=models.CharField(max_length=150,null=True,default="NA")

    def __str__(self):
        return self.ip

templates/accounts/UnPaidOrders.html
{% extends 'base.html' %}
{% block content %}
{% load i18n %}
{% block title %}My uncompleted orders{% endblock %}
<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content padding-y bg">
    <br>
    <br>
    <br>
    <br>
<!--{% include 'includes/alerts.html' %}-->

<div class="container">
	<div class="row">
{% include 'includes/dashboardSide.html'%}
	<main class="col-9">
		<article class="card">
		<header class="card-header">
			<strong class="d-inline-block mr-3">{%trans 'My orders:'%} </strong>

		</header>
		<div class="card-body">
			<div class="row">

				<div class="col-md-12">
				<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">{%trans 'Order #'%}</th>
      <th scope="col">{%trans 'Course Name'%}</th>
      <th scope="col">{%trans 'Order Total'%}</th>
      <th scope="col">{%trans 'order Date'%}</th>
      <th scope="col">{%trans 'Status'%}</th>
    </tr>
  </thead>
  <tbody>
  {% for order in UnPaidOrders %}
    <tr>
      <th scope="row"><a href="{% url 'Editplaceorder' order.order_number  %}">{{order.order_number}} </a></th>
      <td>{{order.order_course.course_name}}</td>
      <td>AED {{order.gtotal}}</td>
      <td>{{order.created_at}}</td>

      <td>{%trans 'Not Orderd'%}  </td>

    </tr>
  {% endfor %}

  </tbody>
</table>
				</div>

			</div> <!-- row.// -->
		</div> <!-- card-body .// -->

		</article> <!-- order-group.// -->
	</main>
</div> <!-- row.// -->
</div>


</section>
<!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock %}

templates/accounts/complains.html
{% extends 'base.html' %}
{% block content %}
{% load i18n %}
{% block title %}Complains{% endblock %}
<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content padding-y bg  ">
<!--{% include 'includes/alerts.html' %}-->
    <br>
    <br>
    <br>
    <br>

<div class="container">
	<div class="row d-flex justify-content-center ">

    {% include 'includes/dashboardSide.html'%}

	<main class="col-7">
		<article class="card">
		<header class="card-header">
			<strong class="d-inline-block mr-3"> {%trans 'Complains'%} </strong>

		</header>
		<div class="card-body">
            <div class="text-right">
            </div>
			<div class="row">

				<div class="col-md-12">
				{%if user.is_authenticated  %}


				<form  action="{% url 'complains'  %}" method="POST">
					{% csrf_token %}

						<label>{%trans 'Complain Title(Regards):'%}</label>
						<input required type="text" name="Regards" class="form-control" >
						<br>
						<label>{%trans 'Complain:'%} </label>
						<textarea required name="Reason" rows="4" class="form-control"></textarea>
							<br>
						<input type="submit" value="{%trans 'submit'%}" class="btn btn-success">

					</div>
				</form>

				{%endif %}
				</div>

			</div> <!-- row.// -->
		</div> <!-- card-body .// -->

		</article> <!-- order-group.// -->
	</main>
</div> <!-- row.// -->
</div>


</section>
<!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock %}

templates/accounts/dashboard.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
 {% load i18n %}
 {% block title %}dashboard{% endblock %}
<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content padding-y bg">
<!--{% include 'includes/alerts.html' %}-->
<br>
<br>
<br>
<br>
<br>
<div class="container">
	<div class="row">
{% include 'includes/dashboardSide.html'%}
	<main class="col-9">
		<article class="card">
		<header class="card-header">
			<strong class="d-inline-block mr-3"> {%trans 'login as Student:'%} </strong>
			<span>{{user.first_name}} {{user.last_name}}</span>
		</header>
		<div class="card-body">
			<div class="row">
				<div class="col-md-6">
				<div class="card text-center">
					<div class="card-body">
						<div class="row">
				<div class="col-md-6">
					<div class="card text-center">
						<h5 class="card-title">  {%trans 'Total Courses'%} </h5>
						<h4>{{orders_count}}</h4>
						{%if orders_count%}
						<a href="{%url 'myOrders'%}"> {%trans 'View courses'%}</a>

						{%else%}
						<a href="{%url 'courses'%}"> {%trans 'Choose Course'%}</a>
						{%endif%}
						</div>
				</div>
							<div class="col-md-6">
								<div class="card text-center">



						<h5 class="card-title">  {%trans 'Active Courses'%} </h5>
						<h4>{{active_orders_count}}</h4>
						{%if active_orders_count %}
						<a href="{%url 'myActiveOrders'%}"> {%trans 'View courses'%}</a>
						{%else%}
						<a href="{%url 'courses'%}"> {%trans 'Choose Course'%}</a>
						{%endif%}

							</div>
				</div>
				</div>
						<div class="row  mt-2 ">
							<div class="col-md-6 ">
					<div class="card ">
						<h5 class="card-title">  {%trans 'Last Unpaid orders'%} </h5>
						<h4>{{UnPaidOrders}}</h4>
						{%if UnPaidOrders is not 0 %}
						<a href="{%url 'UnPaidOrders'%}"> {%trans 'View orders'%}</a>

						{%else%}
						<a href="{%url 'courses'%}"> {%trans 'Choose Course'%}</a>
						{%endif%}
						</div>
				</div>


						</div>
					</div>
					</div>
				</div>
				<div class="col-md-6">
				<div class="card text-center">
					<div class="card-body">

				  {% if user.user_img %}
				  <a href="{%url 'editProfile'%}"><img  height="100" class="rounded-circle mb-0" style="margin:20px"  src="{{user.user_img.url}}" alt=" {%trans 'user picture'%}"></a>
						<div>
						<a role="button"  class="btn btn-outline-danger"  href="{% url 'deltePhoto' %}"> {%trans 'Remove Photo'%}</a>
							</div>
				  {% else%}
				 <a href="{%url 'editProfile'%}"> <img  height="100" class="rounded-circle mb-0" style="margin:20px"  src="{% static 'img/default_avatar.png'%}" alt=" {%trans 'user picture'%}"></a>
				  {% endif %}

						<p class="mb-0">{{user.email}}</p>
						<p>{{user.phone}}</p>
					</div>
					</div>
				</div>

			</div> <!-- row.// -->
		</div> <!-- card-body .// -->


		</article> <!-- order-group.// -->
	</main>
</div> <!-- row.// -->
</div>


</section>
<!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock %}

templates/accounts/message_form.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
{% load i18n %}
<section class="section-content padding-y bg">
<br>
<br>
<br>
<br>

<div class="container ">
<div class="email-app">
    <nav>
        <a href="{% url 'createMessage' 0 %}" class="btn btn-danger btn-block">{%trans 'New Email'%}</a>
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'inbox'%}"><i class="fa fa-inbox"></i> {%trans 'Inbox'%} <span class="badge badge-danger">{{unreadCount}}</span></a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{% url 'inbox'%}"><i class="fa fa-rocket"></i> {%trans 'Sent'%}</a>
            </li>



        </ul>
    </nav>
    <main>
        <p class="text-center">{%trans 'New Message'%}</p>
        <form method="POST" action="{%url 'createMessage' 0 %}">
            {%csrf_token%}
            <div class="form-row ">
                <label  class="col-2 col-sm-1 col-form-label">{%trans 'To:'%}</label>
                <div class="col-10 col-sm-11 mb-3">
                           {{form.recipient}}
                </div>
            </div>
            <div class="form-row mb-3">
                <label  class="col-2 col-sm-1 col-form-label">{%trans 'Subject:'%}</label>
                <div class="col-10 col-sm-11">

                   {{form.subject}}

                </div>
            </div>


        <div class="form-row">
              <label  class="col-2 col-sm-1 col-form-label">{%trans 'Message:'%}</label>
            <div class="col-sm-11 ml-auto">

                <div class="form-group mt-4">

                   {{form.body}}
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-success">{%trans 'Send'%}</button>
                    </form>
                   <a href="{%url 'inbox'%}" class="btn btn-danger">{%trans 'Discard'%}</a>
                </div>

            </div>
        </div>
    </main>
</div>
</div>
</section>

<style type="text/css">
.email-app {
    display: flex;
    flex-direction: row;
    background: #fff;
    border: 1px solid #e1e6ef;
}

.email-app nav {
    flex: 0 0 200px;
    padding: 1rem;
    border-right: 1px solid #e1e6ef;
}

.email-app nav .btn-block {
    margin-bottom: 15px;
}

.email-app nav .nav {
    flex-direction: column;
}

.email-app nav .nav .nav-item {
    position: relative;
}

.email-app nav .nav .nav-item .nav-link,
.email-app nav .nav .nav-item .navbar .dropdown-toggle,
.navbar .email-app nav .nav .nav-item .dropdown-toggle {
    color: #151b1e;
    border-bottom: 1px solid #e1e6ef;
}

.email-app nav .nav .nav-item .nav-link i,
.email-app nav .nav .nav-item .navbar .dropdown-toggle i,
.navbar .email-app nav .nav .nav-item .dropdown-toggle i {
    width: 20px;
    margin: 0 10px 0 0;
    font-size: 14px;
    text-align: center;
}

.email-app nav .nav .nav-item .nav-link .badge,
.email-app nav .nav .nav-item .navbar .dropdown-toggle .badge,
.navbar .email-app nav .nav .nav-item .dropdown-toggle .badge {
    float: right;
    margin-top: 4px;
    margin-left: 10px;
}

.email-app main {
    min-width: 0;
    flex: 1;
    padding: 1rem;
}

.email-app .inbox .toolbar {
    padding-bottom: 1rem;
    border-bottom: 1px solid #e1e6ef;
}

.email-app .inbox .messages {
    padding: 0;
    list-style: none;
}

.email-app .inbox .message {
    position: relative;
    padding: 1rem 1rem 1rem 2rem;
    cursor: pointer;
    border-bottom: 1px solid #e1e6ef;
}

.email-app .inbox .message:hover {
    background: #f9f9fa;
}

.email-app .inbox .message .actions {
    position: absolute;
    left: 0;
    display: flex;
    flex-direction: column;
}

.email-app .inbox .message .actions .action {
    width: 2rem;
    margin-bottom: 0.5rem;
    color: #c0cadd;
    text-align: center;
}

.email-app .inbox .message a {
    color: #000;
}

.email-app .inbox .message a:hover {
    text-decoration: none;
}

.email-app .inbox .message.unread .header,
.email-app .inbox .message.unread .title {
    font-weight: bold;
}

.email-app .inbox .message .header {
    display: flex;
    flex-direction: row;
    margin-bottom: 0.5rem;
}

.email-app .inbox .message .header .date {
    margin-left: auto;
}

.email-app .inbox .message .title {
    margin-bottom: 0.5rem;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
}

.email-app .inbox .message .description {
    font-size: 12px;
}

.email-app .message .toolbar {
    padding-bottom: 1rem;
    border-bottom: 1px solid #e1e6ef;
}

.email-app .message .details .title {
    padding: 1rem 0;
    font-weight: bold;
}

.email-app .message .details .header {
    display: flex;
    padding: 1rem 0;
    margin: 1rem 0;
    border-top: 1px solid #e1e6ef;
    border-bottom: 1px solid #e1e6ef;
}

.email-app .message .details .header .avatar {
    width: 40px;
    height: 40px;
    margin-right: 1rem;
}

.email-app .message .details .header .from {
    font-size: 12px;
    color: #9faecb;
    align-self: center;
}

.email-app .message .details .header .from span {
    display: block;
    font-weight: bold;
}

.email-app .message .details .header .date {
    margin-left: auto;
}

.email-app .message .details .attachments {
    padding: 1rem 0;
    margin-bottom: 1rem;
    border-top: 3px solid #f9f9fa;
    border-bottom: 3px solid #f9f9fa;
}

.email-app .message .details .attachments .attachment {
    display: flex;
    margin: 0.5rem 0;
    font-size: 12px;
    align-self: center;
}

.email-app .message .details .attachments .attachment .badge {
    margin: 0 0.5rem;
    line-height: inherit;
}

.email-app .message .details .attachments .attachment .menu {
    margin-left: auto;
}

.email-app .message .details .attachments .attachment .menu a {
    padding: 0 0.5rem;
    font-size: 14px;
    color: #e1e6ef;
}

@media (max-width: 767px) {
    .email-app {
        flex-direction: column;
    }
    .email-app nav {
        flex: 0 0 100%;
    }
}

@media (max-width: 575px) {
    .email-app .message .header {
        flex-flow: row wrap;
    }
    .email-app .message .header .date {
        flex: 0 0 100%;
    }
}
</style>

<script type="text/javascript">
 $(document).ready(function() {
    if (window.location.href.indexOf("reply") > -1) {
        var txt = $('#id_subject');
      txt.val("RE: " + txt.val());
    }
  });

</script>
{% endblock %}

templates/accounts/register.html
{% extends 'base.html' %}
{% block content %}
{% load i18n %}
{% block title %}Register{% endblock %}
<!-- ========================= SECTION CONTENT ========================= -->
<style>
@import url(https://fonts.googleapis.com/css?family=Roboto:500);
   /* The message box is shown when the user clicks on the password field */
#message {
  display:none;
  background: #f1f1f1;
  color: #000;
  position: relative;
  padding: 20px;
  margin-top: 10px;
}

#message p {
  padding: 2px 35px;
  font-size: 12px;
}

/* Add a green text color and a checkmark when the requirements are right */
.valid {
  color: green;
}

.valid:before {
  position: relative;

  content: "✔";
  float:left;
}

/* Add a red text color and an "x" when the requirements are wrong */
.invalid {
  color: red;
}

.invalid:before {
  position: relative;
  content: "✖";
  float:left;

}

.google-btn {
  width: 184px;
  height: 42px;
  background-color: #4285f4;
  border-radius: 2px;
  box-shadow: 0 3px 4px 0 rgba(0, 0, 0, 0.25);
}
.google-btn .google-icon-wrapper {
  float: left;
  margin-top: 1px;
  margin-left: 1px;
  width: 40px;
  height: 40px;
  border-radius: 2px;
  background-color: #fff;
}
.google-btn .google-icon {
  float: inherit;

  margin-top: 11px;
  margin-left: 11px;
  width: 18px;
  height: 18px;
}
.google-btn .btn-text {
  float: right;
  margin: 11px 11px 0 0;
  color: #fff;
  font-size: 14px;
  letter-spacing: 0.2px;
  font-family: "Roboto";
}
.google-btn:hover {
  box-shadow: 0 0 6px #4285f4;
}
.google-btn:active {
  background: #1669f2;
}
</style>
<section class="section-content pb-0">

<!-- ============================ COMPONENT REGISTER   ================================= -->
	<br>
	<br>
	<br>
	<br>
	<div class="card mx-auto" style="max-width:700px; margin-top:40px;">
      <article class="card-body">
		<header class="mb-4"><h4 class="card-title text-center">{%trans 'Sign up'%}</h4></header>
		<form action="{%url 'register'%}" method="POST" data-url="{% url 'register' %}" enctype= multipart/form-data id="stud_registration_form">
			{%csrf_token%}

							<div class="form-row">
					<div class="col form-group ">
<!--						<label>First name</label>-->
						{{form.first_name}}
					</div> <!-- form-group end.// -->
					<div class="col form-group ">
<!--						<label>Last name</label>-->
					  	{{form.last_name}}
					</div> <!-- form-group end.// -->
				</div> <!-- form-row end.// -->
<!--				<div class="form-group">-->
<!--					<label>Email</label>-->
<!--						{{form.email}}-->
<!--					<small class="form-text text-muted">We'll never share your email with anyone else.</small>-->
<!--				</div> &lt;!&ndash; form-group end.// &ndash;&gt;-->

				<div class="form-row">
					<div class="form-group ">
<!--						<label>Email</label>-->
						{{form.email}}
					<small class="form-text text-danger" id="stud_email_err">{%trans 'Email address already exists! Use another one or log in'%}.</small>
					</div> <!-- form-group end.// -->
					<div class="form-group ">
<!--					  <label>phone No.</label>-->
							{{form.phone}}
					</div> <!-- form-group end.// -->


				</div> <!-- form-row.// -->
				<div class="form-row">
					<div class="form-group ">
<!--						<label>Create password</label>-->
						{{form.password}}

					</div> <!-- form-group end.// -->
					<div class="form-group ">
<!--						<label>Repeat password</label>-->
					 {{form.confirm_password}}
					</div> <!-- form-group end.// -->
				</div>
			    <div class="form-group">
			        <button type="submit" id="submi" disabled class="btn btn-primary btn-block">{%trans 'Register'%}   </button>
			    </div> <!-- form-group// -->
				{{form.email.errors}}

			{{form.non_field_errors}}
			</form>
		</article><!-- card-body.// -->
		<div class="text-center" id="message">
                      <h5>Password must contain the following</h5>
                      <p id="letter" class="invalid ">A <b>lowercase</b> letter</p>
                      <p id="capital" class="invalid">A <b>capital (uppercase)</b> letter</p>
                      <p id="number" class="invalid">A <b>number</b></p>
                      <p id="length" class="invalid">Minimum <b>8 characters</b></p>
                      <p id="ccon" class="invalid">password and confirm password <b>match</b></p>
                    </div>
				</div>
    </div> <!-- card .// -->
	<p class="text-center mt-4">{%trans 'Have an account?'%} <a href="{%url 'login'%}">{%trans 'Log In'%}</a></p>
	<p class="text-center mt-4">{%trans 'Are you Teacher?'%} <a href="{%url 'teacherProfile'%}">{%trans 'Register as a teacher'%}</a></p>


<!-- ============================ COMPONENT REGISTER  END.// ================================= -->


</section>
<link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Open+Sans" />
<div class="container d-flex justify-content-center mb-4">
<a  href="{% url 'social:begin' 'google-oauth2' %}">
<div class="google-btn">
  <div class="google-icon-wrapper">
    <img class="google-icon" src="https://upload.wikimedia.org/wikipedia/commons/5/53/Google_%22G%22_Logo.svg"/>

  </div>
  <p class="btn-text"><b>Sign in with google</b></p>
</div>
  </a>
</div>
<script>
// =======================================ajax

function emailError(error) {
  if (!error) {

    $("#stud_email_err").hide();
    $("#id_email").css("border-bottom", "2px solid #34F458");
  } else {

    $("#stud_email_err").show();
    $("#id_email").css("border-bottom", "2px solid #F90A0A");
  }
}

$("#id_email").keyup(function() {

  const email = $(this).val();
  $.ajax({
    data: $(this).serialize(),
    url: $(this).closest('form').data("url"),
    success: function(response) {

      if (response.is_taken) {


        emailError("Email address already exists! Use another one or log in");
      } else {

        emailError(null);
      }

    },
    error: function(response) {
      console.log(response.errors);
    },
  });
});
// =======================================ajax
var CustomerAcctNumber = document.getElementById("id_password");
CustomerAcctNumber.setAttribute("pattern","(?=.*\\d)(?=.*[a-z])(?=.*[A-Z]).{8,}");
CustomerAcctNumber.setAttribute("title","Must contain at least one  number and one uppercase and lowercase letter, and at least 8 or more characters");

var myInput = document.getElementById("id_password");
var letter = document.getElementById("letter");
var capital = document.getElementById("capital");
var number = document.getElementById("number");
var length = document.getElementById("length");
var conf = document.getElementById("id_confirm_password");

// When the user clicks on the password field, show the message box
myInput.onfocus = function() {
  document.getElementById("message").style.display = "block";
}
conf.onfocus = function() {
  document.getElementById("message").style.display = "block";
}

myInput.onblur = function() {
  document.getElementById("message").style.display = "none";
}
conf.onblur = function() {
  document.getElementById("message").style.display = "none";
}

// When the user starts to type something inside the password field
myInput.onkeyup = function() {
  // Validate lowercase letters
  var lowerCaseLetters = /[a-z]/g;
  if(myInput.value.match(lowerCaseLetters)) {
    letter.classList.remove("invalid");
    letter.classList.add("valid");
  } else {
    letter.classList.remove("valid");
    letter.classList.add("invalid");
  }

  // Validate capital letters
  var upperCaseLetters = /[A-Z]/g;
  if(myInput.value.match(upperCaseLetters)) {
    capital.classList.remove("invalid");
    capital.classList.add("valid");
  } else {
    capital.classList.remove("valid");
    capital.classList.add("invalid");
  }

  // Validate numbers
  var numbers = /[0-9]/g;
  if(myInput.value.match(numbers)) {
    number.classList.remove("invalid");
    number.classList.add("valid");
  } else {
    number.classList.remove("valid");
    number.classList.add("invalid");
  }

  // Validate length
  if(myInput.value.length >= 8) {
    length.classList.remove("invalid");
    length.classList.add("valid");
  } else {
    length.classList.remove("valid");
    length.classList.add("invalid");
  }
}

  conf.onkeyup =  function() {
  if(myInput.value == conf.value) {

    ccon.classList.remove("invalid");
    ccon.classList.add("valid");

    $('#submi').prop('disabled', false);
     document.getElementById("message").style.display = "none";



  } else {
    ccon.classList.remove("valid");
    ccon.classList.add("invalid");
    $('#submi').prop('disabled', true)



  }

  }


</script>
{% endblock %}